import { GuideNode } from '@/types/guide';

export const Guide_NODES: GuideNode[] = [
    {
        "id": "9cd0b37b-510d-44cb-86a9-0de1e91ceddd",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 10,
        "title": "The Setup",
        "description": "Build a profile that looks like a veteran, not a spammer.",
        "content": "# The 5-Year Veteran Disguise\n\nReddit users have a sixth sense for \"Marketroids\". Your goal today is to become invisible.\n\n## 1. The \"Human\" Test\n- **Avatar:** Do NOT use your company logo. Use a picture of you, or a stylized Snoo.\n- **Bio:** Write established interests, not a sales pitch.\n    - *Bad:* \"CEO of SaaSTool. We help you...\"\n    - *Good:* \"Indie dev building tools for productivity. Coffee addict.\"\n\n---\n\n## 2. The Keyword Net (Critical)\n\nYour keywords are your radar. Bad keywords = empty feeds.\n\n### ✅ Good Keywords (High Intent)\n| Type | Example | Why |\n|------|---------|-----|\n| **Pain Phrases** | \"tired of\", \"hate when\" | Catches people with problems |\n| **Comparison** | \"[Competitor] alternative\" | People evaluating options |\n| **Questions** | \"how do you\", \"best way to\" | People seeking solutions |\n\n### ❌ Bad Keywords\n- Too broad: \"marketing\", \"software\"\n- Your brand name (too early)\n- Generic verbs: \"help\", \"grow\"\n\n### 🎯 The Keyword Formula\nStart with exactly 2-3 word keywords:\n1. **Pain:** \"hate [competitor]\"\n2. **Question:** \"how to track [problem]\"\n3. **Niche:** \"[specific industry term]\"\n\n---\n\n## ⚠️ Safety Check\nIf your account is **< 48 hours old**:\n- Do NOT post\n- Max 5 comments/day\n- Just subscribe and upvote",
        "action_link": "?tab=settings",
        "action_label": "Setup Keywords",
        "day_number": 1,
        "estimated_minutes": 20
    },
    {
        "id": "08d36836-47da-4bc4-8715-9e0e9c5b9327",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 20,
        "title": "The Listener",
        "description": "Identify target communities and learn their language.",
        "content": "# Read the Room\n\nBefore you speak, you must listen. Every subreddit has its own culture.\n\n## Task\n1. Go to **Command Center**\n2. Look at \"Top\" posts in your discovered subreddits\n3. Note the lingo: \"SaaS\" vs \"Micro-SaaS\"? \"Clients\" vs \"Custies\"?\n\n## Why?\nUsing the wrong word marks you as an outsider instantly.\n\n## 🕒 The 9:1 Rule\nFor every **1 self-promotion**, make **9 genuine contributions**.\nStart your \"9\" today by upvoting good content.",
        "action_link": "?tab=live",
        "action_label": "Go to Command Center",
        "day_number": 2,
        "estimated_minutes": 30
    },
    {
        "id": "372b9d74-ae74-4371-bb95-b4887db78cb5",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 30,
        "title": "The Sniper DM",
        "description": "Get your first user without posting publicly.",
        "content": "# The Shadow Strategy\n\nYou have 0 Karma. You cannot post. But you CAN message.\n\n## The Strategy\n1. Find a user in **Command Center** complaining about a competitor\n2. Click \"View on Reddit\"\n3. Send a **Helpful DM**\n\n### The Script\n\"Hey! Saw your post about [Competitor]. I built a tiny tool that fixes [Pain]. Free to try, no credit card. [Link] Let me know if it sucks!\"\n\n## 🛑 DANGER ZONE\n- **Max:** 3 DMs per day\n- **Timing:** 15+ minutes between DMs\n- 10 DMs in an hour = shadowban",
        "action_link": "?tab=live",
        "action_label": "Find a Lead",
        "day_number": 3,
        "estimated_minutes": 15
    },
    {
        "id": "7f268e51-e1a2-47a6-b3a5-f540fd27e5e2",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 40,
        "title": "The Me-Too Comment",
        "description": "Validate others to build karma.",
        "content": "# The \"This!\" Comment\n\nEasiest way to get karma? Validate angry people.\n\n## The Tactic\n1. Find a \"Rant\" post\n2. Comment agreeing with them\n3. Share a *personal* anecdote\n4. **DO NOT LINK YOUR TOOL**\n\n### Example\n\"Man, I feel this. Spent 3 weeks fighting [Competitor] API last year. Nightmare.\"\n\n## 🕒 Best Time to Comment\n- **< 1 Hour old:** Gold mine (top comment potential)\n- **> 12 Hours:** Graveyard (no one will see you)",
        "action_link": "?tab=live",
        "action_label": "Find a Rant",
        "day_number": 5,
        "estimated_minutes": 10
    },
    {
        "id": "0d37ad2a-3871-4bdf-9ba3-579143be9610",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 50,
        "title": "The Listicle",
        "description": "Draft a \"Top Tools\" list to subtly position your product.",
        "content": "# The Trojan List\n\nPeople love lists. High engagement. We slide your product in.\n\n## The Formula\n\"Top 5 Tools for [Problem]\":\n1. The Giant (standard advice)\n2. The Open Source option\n3. **Your Product** (the \"Specialist\")\n4. A Niche Alternative\n5. The Weird One\n\n## ⚠️ The Humble Rule\nPut yourself at #3 or #4. Never #1. Looks less biased.",
        "action_link": null,
        "action_label": null,
        "day_number": 8,
        "estimated_minutes": 45
    },
    {
        "id": "3994583a-acc6-47c6-a6d2-a408d9612a95",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 60,
        "title": "The First Post",
        "description": "Share your founder story in a safe space.",
        "content": "# The Origin Story\n\nSubreddits like r/SideProject and r/IndieHackers *want* you to succeed.\n\n## Task\n1. Draft a story: \"I was tired of [Problem], so I built this\"\n2. Be vulnerable. Share the struggle.\n3. **No links in body.** Put link in comments.\n\n## 🛑 Strict Rules\n- Post to **1 subreddit** today only\n- Do not blast 5 at once\n\n## Goals\n- 10+ Upvotes\n- 3+ Comments",
        "action_link": null,
        "action_label": null,
        "day_number": 10,
        "estimated_minutes": 60
    },
    {
        "id": "f8d69711-f97d-4ab5-a8d6-a4631c885df2",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 70,
        "title": "The AMA Play",
        "description": "Host an informal AMA in a friendly subreddit.",
        "content": "# The Casual AMA\n\nAMAs position you as an expert without selling.\n\n## Best Subreddits\n- r/SideProject\n- r/InternetIsBeautiful  \n- r/startups (if you have traction)\n\n## Title Formula\n\"I built [Tool] that does [Benefit]. Happy to answer any questions!\"\n\n## Rules\n- Answer EVERY comment within 2 hours\n- Be honest about failures\n- Only link if directly asked\n\n## Goal\n- Build your comment history\n- Get organic profile visits",
        "action_link": null,
        "action_label": null,
        "day_number": 14,
        "estimated_minutes": 90
    },
    {
        "id": "4722ce85-3cb7-4c29-9f53-2e52ecc188a1",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 80,
        "title": "The Case Study Comment",
        "description": "Share your story in relevant threads.",
        "content": "# The \"How I Did It\" Comment\n\nFind posts asking \"how did you get your first users?\" and share YOUR story.\n\n## Where to Find\nSearch: \"first users\" OR \"first customers\" OR \"how did you get\"\n\n## Template\n\"For my tool [Name], I got my first 20 users by:\n1. [Tactic 1]\n2. [Tactic 2]\n3. [Tactic 3]\n\nThe #1 thing that worked was [X]. Happy to share more details.\"\n\n## Why It Works\nPeople asking = people building = potential users",
        "action_link": "?tab=live",
        "action_label": "Search Threads",
        "day_number": 18,
        "estimated_minutes": 20
    },
    {
        "id": "eb4962b2-8682-4c05-b47f-68c888992391",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 90,
        "title": "The Lead Magnet",
        "description": "Scale outreach with free value.",
        "content": "# Give to Get\n\nStop selling the tool. Sell the *result*.\n\n## The Tactic\n1. Create a free PDF, Calculator, or Template\n2. Search for \"How to [X]?\" posts\n3. Reply: \"I made a free calculator for this. [Link]\"\n\n## The Hook\nCalculator is free. \"Save Results\" button? Requires your SaaS.\n\n## 🕒 Limits\n- Max 5 replies/day with this method\n- Vary phrasing every time",
        "action_link": null,
        "action_label": null,
        "day_number": 22,
        "estimated_minutes": 45
    },
    {
        "id": "b3b4bcea-4623-4da3-ad9b-7dc80abd4aa5",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 100,
        "title": "The Free Tool Play",
        "description": "Create a standalone micro-tool.",
        "content": "# The Trojan Tool\n\nBuild something small that solves ONE micro-problem.\n\n## Examples\n- If you sell analytics: Free \"Page Speed Checker\"\n- If you sell email tools: Free \"Subject Line Grader\"\n- If you sell project mgmt: Free \"Meeting Cost Calculator\"\n\n## The Flow\n1. Tool is 100% free, no signup\n2. Results page has: \"Want to save this? Try [Main Product]\"\n3. Share tool in relevant subreddits\n\n## Why It Works\nFree tool = sharable = organic growth",
        "action_link": null,
        "action_label": null,
        "day_number": 28,
        "estimated_minutes": 120
    },
    {
        "id": "7493bc99-be9c-4e64-bdae-93b26f298af8",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 110,
        "title": "The Weekly Roundup",
        "description": "Become the curator in your niche.",
        "content": "# The \"Best Of\" Strategy\n\nPost weekly roundups of best tools/resources in your niche.\n\n## Format\n\"This Week in [Niche]: Best Tools & Resources\"\n- Tool 1: [Description]\n- Tool 2: [Description]\n- **Your Tool**: [Description]\n- Tool 4: [Description]\n\n## Where to Post\n- Your niche subreddits\n- r/SideProject\n- Relevant Discord communities\n\n## Consistency\nSame day, same time, every week. Build expectation.",
        "action_link": null,
        "action_label": null,
        "day_number": 35,
        "estimated_minutes": 30
    },
    {
        "id": "8645310d-d87d-4812-905f-09d71e84c991",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 120,
        "title": "The Warm DM 2.0",
        "description": "Re-engage previous positive contacts.",
        "content": "# The Follow-Up\n\nRemember people who responded positively? Time to re-engage.\n\n## Template\n\"Hey [Name]! Remember when you mentioned [Pain Point]? I just added [Feature] that solves exactly that. Thought you'd want to know. No pressure, just wanted to share!\"\n\n## Rules\n- Only message people who responded positively before\n- Max 5 per week\n- Be genuinely helpful, not pushy\n\n## Why It Works\nWarm leads convert 5-10x better than cold",
        "action_link": null,
        "action_label": null,
        "day_number": 40,
        "estimated_minutes": 15
    },
    {
        "id": "67aa5d5d-76d5-4326-8799-447cf8edd425",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 4,
        "order_index": 130,
        "title": "The Ultimate Guide",
        "description": "Write THE definitive resource for your niche.",
        "content": "# The 2000-Word Play\n\nWrite the most comprehensive guide on your topic. Become the reference.\n\n## Structure\n1. **Problem Overview** (why this matters)\n2. **Common Mistakes** (what people do wrong)\n3. **The Framework** (your solution)\n4. **Tools** (including yours, naturally)\n5. **Action Steps** (what to do today)\n\n## Where to Post\n- r/Entrepreneur\n- r/startups\n- Your main niche subreddit\n\n## Goal\nGet saved, bookmarked, and referenced by others",
        "action_link": null,
        "action_label": null,
        "day_number": 46,
        "estimated_minutes": 180
    },
    {
        "id": "4aa2e284-3935-4b7c-b2f5-0bd0f502733e",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 4,
        "order_index": 140,
        "title": "The Comment Domination",
        "description": "Become the most helpful voice in your niche.",
        "content": "# The Daily 3\n\nSet a daily goal: 3 high-value comments on trending posts.\n\n## What Makes a High-Value Comment?\n- Adds new information\n- Shares personal experience\n- Provides actionable advice\n- NOT just \"Great post!\"\n\n## Process\n1. Check RedLeads for trending posts\n2. Pick 3 where you can add value\n3. Write 2-3 paragraph responses\n4. No self-promotion\n\n## The Compound Effect\n30 days × 3 comments = 90 touchpoints of authority",
        "action_link": "?tab=live",
        "action_label": "Find Trending Posts",
        "day_number": 50,
        "estimated_minutes": 20
    },
    {
        "id": "7d699ac3-9916-49bd-814a-c9e531937883",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 4,
        "order_index": 150,
        "title": "The Founder Story Thread",
        "description": "Share your transparent journey.",
        "content": "# The Vulnerability Play\n\nReddit loves transparency. Share your real numbers and struggles.\n\n## Template\n\"Building [Product] in public: [Month] Update\"\n- MRR: $X → $Y\n- Users: X → Y\n- What worked: [Details]\n- What failed: [Details]\n- Biggest learning: [Details]\n\n## Where to Post\n- r/SideProject\n- r/EntrepreneurRideAlong\n- r/startups\n\n## Why It Works\nPeople root for underdogs. Transparency builds trust.",
        "action_link": null,
        "action_label": null,
        "day_number": 60,
        "estimated_minutes": 45
    },
    {
        "id": "d8f1ad56-f235-4223-81ba-8703e7f05782",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 4,
        "order_index": 160,
        "title": "The Collaboration Post",
        "description": "Partner with another maker.",
        "content": "# The Crossover Episode\n\nFind another indie maker and create something together.\n\n## Ideas\n- Joint comparison: \"We both built [Category] tools. Here's our honest take.\"\n- Integration: \"We connected [Your Tool] + [Their Tool]. Here's what happened.\"\n- Challenge: \"We both tried [Strategy] for 30 days. Results inside.\"\n\n## How to Find Partners\n- r/SideProject comments\n- IndieHackers\n- Twitter #buildinpublic\n\n## Why It Works\n2 audiences > 1 audience",
        "action_link": null,
        "action_label": null,
        "day_number": 70,
        "estimated_minutes": 60
    },
    {
        "id": "0f8b8360-945c-4494-a9cf-b0e525cdbedf",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 5,
        "order_index": 170,
        "title": "The Alert Automation",
        "description": "Systematize your Reddit monitoring.",
        "content": "# The Passive Pipeline\n\nSet up RedLeads to auto-notify you of opportunities.\n\n## Setup\n1. Go to Tracking Setup\n2. Add 10-15 high-intent keywords\n3. Enable daily email alerts\n4. Check alerts every morning\n\n## Keyword Categories\n- Pain keywords (5)\n- Question keywords (5)\n- Competitor keywords (3-5)\n\n## Daily Routine\nMorning coffee + RedLeads alerts = 30 min/day for leads",
        "action_link": "?tab=settings",
        "action_label": "Configure Alerts",
        "day_number": 76,
        "estimated_minutes": 15
    },
    {
        "id": "beba3a4a-1920-44a6-ba13-4ee5b3bb9993",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 5,
        "order_index": 180,
        "title": "The Response Template Library",
        "description": "Build your swipe file.",
        "content": "# The Efficiency Engine\n\nCreate 5-10 response templates for common situations.\n\n## Template Categories\n1. **Pain Validator:** Empathize → Share experience → Soft mention\n2. **Question Answer:** Direct answer → Context → \"I use [Tool] for this\"\n3. **Comparison Response:** Acknowledge both → Your perspective → Why\n4. **Help Offer:** Solution → Free resource → Optional tool mention\n5. **Story Share:** Personal experience → Learning → What I built\n\n## Rules\n- NEVER copy-paste directly\n- Always personalize 20%+\n- Rotate templates to avoid patterns",
        "action_link": null,
        "action_label": null,
        "day_number": 80,
        "estimated_minutes": 60
    },
    {
        "id": "f09c893e-f70b-47f1-8ef8-372fc6382f3e",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 5,
        "order_index": 190,
        "title": "The Subreddit Deep Dive",
        "description": "Become a known name in 3 communities.",
        "content": "# The Home Base Strategy\n\nPick your top 3 performing subreddits. Go deep.\n\n## Selection Criteria\n- Where did your best leads come from?\n- Where did you get most upvotes?\n- Where is competition lowest?\n\n## Deep Dive Tactics\n- Comment on every relevant post\n- Learn moderators' preferences\n- Understand peak posting times\n- Build relationships with regulars\n\n## Goal\nWhen your topic comes up, YOU get tagged.",
        "action_link": null,
        "action_label": null,
        "day_number": 85,
        "estimated_minutes": 30
    },
    {
        "id": "f8c042cc-9774-4dd5-a9a0-4b03f5a113cc",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 5,
        "order_index": 200,
        "title": "The Celebration Post",
        "description": "Hit 100 users? Tell Reddit.",
        "content": "# The Milestone Moment\n\nYou made it. Now share the journey.\n\n## The Post\n\"I just hit 100 users from Reddit. Here's exactly how I did it.\"\n\n## Include\n- Timeline (how long it took)\n- Top 3 tactics that worked\n- Top 3 mistakes you made\n- Actual numbers (be transparent)\n- Lessons for others starting out\n\n## Where to Post\n- r/Entrepreneur\n- r/startups\n- r/SideProject\n- Your niche subreddits\n\n## Why This Works\nMilestone posts go viral. Your 100 becomes 500.",
        "action_link": null,
        "action_label": null,
        "day_number": 90,
        "estimated_minutes": 60
    }
];
