import { GuideNode } from '@/types/guide';

export const Guide_NODES: GuideNode[] = [
    {
        "id": "day-1-audit",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 10,
        "title": "Account Health Audit",
        "description": "Run an automated shadowban check and configure a low-risk, high-converting profile bio.",
        "content": "# The Account Audit Protocol\n\nReddit's anti-spam filters are incredibly aggressive. If you start promoting your product on a brand-new or unoptimized account, you will face an instant ban. Before posting anything, follow this exact health audit checklist:\n\n## 1. Verify Shadowban Status (Automated Check)\nReddit frequently shadowbans accounts silently. Your posts look live to you, but are invisible to everyone else.\n- Go to **[r/ShadowBan](https://reddit.com/r/ShadowBan)**.\n- Submit a simple text post with any title (e.g., \"Am I shadowbanned?\") and leave the body empty.\n- An automated bot will reply to your post within 30 seconds confirming whether your account is clean, shadowbanned, or restricted.\n\n## 2. Hard Privacy Calibration\nTo prevent Reddit's automated systems from flagging your growth tasks as commercial tracking, disable personalization metrics:\n- Open **Reddit Settings** -> **Safety & Privacy** (`reddit.com/settings/privacy`).\n- Turn off **Personalize ads based on your activity with our partners**.\n- Turn off **Allow search engines to index your profile** (keeps your early testing discrete).\n\n## 3. Passive Conversion Profile Setup\nYour Reddit profile is your passive landing page. When users click your username, they should see a warm, personal bio, not a corporate sales pitch.\n- **Username:** Use a human username (e.g., `u/dan_builder` rather than `u/redleads_official`).\n- **Display Name:** Use your real first name + role (e.g., \"Dan | Founder of RedLeads\").\n- **Avatar:** Use a friendly personal photo or custom avatar rather than a brand logo.\n- **Bio:** Use one of the copy-pasteable templates in the sidebar to write a direct, value-first intro containing your URL.",
        "action_link": "https://www.reddit.com/settings/profile",
        "action_label": "Optimize Reddit Profile",
        "day_number": 1,
        "estimated_minutes": 15,
        "warning_content": "Never start marketing on an account with less than 30 days age and 50 comment karma. Run the shadowban audit check first, as building karma on a shadowbanned account is a complete waste of time.",
        "target_subreddit": null,
        "suggested_title": "Reddit Founder Bio Templates",
        "ready_to_paste_content": "Template 1 (The Builder):\n\"Building [Product Name] to help founders [solve main pain point]. Sharing transparent insights, SaaS metrics, and startup lessons.\"\n\nTemplate 2 (The Expert):\n\"SaaS builder & engineer. Founder of [Product Name] - [one sentence value proposition]. DM me for free audits on [niche problem].\"\n\nTemplate 3 (The Casual):\n\"Founder at [Product Name]. We automate [manual task] for [target audience]. Helping startups optimize their [metric].\""
    },
    {
        "id": "day-2-karma",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 20,
        "title": "The Karma Shield Protocol",
        "description": "Build high-quality comment karma safely without trigger-happy moderators flagging you.",
        "content": "# Build Your Karma Shield\n\nTo safely mention your product later, you need to establish history as a genuine human contributor. Do not try to rush this step by posting low-effort or generic comments.\n\n## How to Build Karma Genuinely\n1. Identify 2-3 active subreddits that are **completely unrelated** to your SaaS (e.g., hobby, local city, gaming, or general news subreddits).\n2. Find threads with fewer than 10 replies where people are asking for advice or questions.\n3. Write comprehensive, multi-paragraph, highly detailed answers. Your goal is to write the single most helpful answer in that thread.\n4. Do this 3 times a day for 4-5 days.\n\nBy engaging outside your niche first, your account history looks like a real, multi-faceted human to Reddit's spam heuristics rather than a single-track marketer.",
        "action_link": null,
        "action_label": null,
        "day_number": 2,
        "estimated_minutes": 20,
        "warning_content": "Do NOT use 'free karma' subreddits or buy karma accounts. Reddit's spam algorithms flag these accounts immediately upon their first link share."
    },
    {
        "id": "day-3-keywords",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 30,
        "title": "Calibrate Keyword Intent",
        "description": "Set up RedLeads keyword monitoring to track high-intent questions while avoiding spam keywords.",
        "content": "# The 3-Tier Keyword Blueprint\n\nYour feed quality depends on your keyword configuration. To prevent filtering through thousands of useless posts, organize your tracked keywords in Settings into three high-value categories:\n\n## Tier 1: Active Pain Points (High Intent)\nTrack exact phrases people use when looking for a tool. \n*Examples: \"anyone know a tool for\", \"looking for alternative to\", \"struggling with [problem]\"*\n\n## Tier 2: Competitor Research\nTrack competitor names without inflammatory terms. \n*Examples: \"[Competitor] alternative\", \"migrating from [Competitor]\"*\n\n## Tier 3: Contextual Discussions\nTrack broad industry topics to find general discussions where you can drop educational value.\n*Examples: \"automated reporting tool\", \"lead scraping flow\"*\n\nConfigure these now so the RedLeads engine has 24 hours to build a custom matching feed for you.",
        "action_link": "?tab=settings",
        "action_label": "Configure Keywords",
        "day_number": 3,
        "estimated_minutes": 10,
        "warning_content": "Never track phrases like 'hate [Competitor]' or 'tired of [Competitor]'. If you jump into competitor threads with aggressive pitches, mods will instantly ban your domain."
    },
    {
        "id": "day-4-rules",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 40,
        "title": "Decode Subreddit Rules",
        "description": "Understand self-promotion rules and identify weekly promotional threads in target subreddits.",
        "content": "# The Subreddit Rules Cheat Sheet\n\nEach subreddit operates like a small, sovereign country. What is allowed in one will get you banned in another. \n\n## Major Subreddits & Self-Promo Policies\n- **r/startups:** Strict ban on direct promotion or links in posts/comments. You can only share your link in the designated monthly \"Share Your Startup\" thread.\n- **r/Entrepreneur:** Allows self-promotion if you disclose your affiliation and provide an extensive, educational text post detailing how you built the business.\n- **r/SaaS:** Highly tolerant of launch announcements, case studies, and transparent build-in-public logs. Make sure to share numbers and metrics.\n\n## Action Checklist\n1. Make a list of 5 subreddits where your ideal customers hang out.\n2. Go to each subreddit and read the sidebar/rules section thoroughly.\n3. Note down if they have dedicated promo days (e.g., \"Self-Promo Sundays\"). Set a recurring calendar reminder to post on those days.",
        "action_link": null,
        "action_label": null,
        "day_number": 4,
        "estimated_minutes": 15,
        "warning_content": "Reddit moderators can view your deleted comments and your entire history. Disclose that you are the founder if you mention your own product—deceiving users will ruin your brand's reputation.",
        "target_subreddit": "r/SaaS",
        "suggested_title": "I spent 120 hours building a tool because I was tired of getting banned on Reddit. Here is what I learned.",
        "ready_to_paste_content": "Hey everyone,\n\nI wanted to share my experience building a software project over the past two months. Like many here, I struggled with getting early traction for my apps. I tried posting on Reddit, but got my domains banned or comments downvoted instantly because I sounded like a marketer.\n\nOut of frustration, I built a small dashboard to track keyword mentions and write value-first replies without looking spammy.\n\nHere are the 3 biggest lessons I learned about Reddit acquisition while building this:\n\n1. Don't Pitch Your Solution, Solve the Pain: If someone asks 'how do I track mentions', I don't link my tool. I explain the exact manual setups (F5Bot, Google Alerts) first. Value-first comments get upvotes.\n2. The Profile Bio is a Passive Funnel: Your comments should drive profile clicks, not link clicks. Keep a clean, friendly bio with your SaaS link.\n3. Automated DMs are Toxic: Never cold DM. Only DM people who explicitly reply asking for the link.\n\nI eventually packaged this setup into a tool called RedLeads to help other builders monitor discussions safely. If you have any feedback or want me to check if your account is currently shadowbanned, drop your username in the comments and I'd love to audit it for you!"
    },
    {
        "id": "day-5-routine",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 50,
        "title": "The 10-Minute Daily Engine",
        "description": "Establish a highly efficient daily routine to respond to high-intent leads quickly.",
        "content": "# Establish the Daily Routine\n\nYou do not need to sit on Reddit all day. In fact, doing so usually leads to desperate, low-quality posts. Instead, execute this exact 10-minute check every morning:\n\n## The Workflow\n1. Open your **Command Center** in RedLeads.\n2. Filter by highest **Match Score** first.\n3. Identify the top 2-3 most relevant posts containing active problems you solve.\n4. Click **Draft Intelligence** on a post to generate a context-aware answer.\n5. Customize the AI's response to make it sound exactly like you (highly casual, conversational, and direct).\n6. Go to Reddit, submit the comment, and close the tab.\n\nConsistency beats marathon sessions. Engaging with 3 target threads a day adds up to nearly 100 high-intent interactions per month.",
        "action_link": "?tab=live",
        "action_label": "Go to Command Center",
        "day_number": 5,
        "estimated_minutes": 10,
        "warning_content": "Always read the original thread manually before posting the AI-drafted reply. AI models can miss sarcasm or specific context, making your reply look automated if left unchecked."
    },
    {
        "id": "day-6-value",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 60,
        "title": "Value-First replies",
        "description": "Structure replies so users get an immediate answer without ever needing to click your link.",
        "content": "# How to Write Value-First Responses\n\nReddit hates marketers, but it loves experts. If your comment starts with \"Hey, check out my app...\", it will be downvoted or deleted. \n\n## The Value-First Comment Anatomy\n1. **The Direct Answer (70% of content):** Genuinely solve their problem. Explain the steps, outline the strategy, or list the free tools they can use to fix it immediately. Provide so much value that they upvote it on merit alone.\n2. **The Soft Pivot (30% of content):** Briefly mention your tool as a shortcut or automation. \n   *Example: \"You can do this manually by scripting X, but if you want to skip that setup, I built [Product] to automate this. Let me know if you want a free trial!\"*\n\nThis format makes it impossible for moderators to delete your comment because it genuinely helps the community.",
        "action_link": "?tab=live",
        "action_label": "Practice on Live Feed",
        "day_number": 6,
        "estimated_minutes": 15,
        "warning_content": "Never drop links directly in comments if you are replying in strict subreddits. Instead, write the answer and say, 'Drop me a DM if you want the link to the tool I built.' This keeps you 100% safe.",
        "target_subreddit": "r/SideProject",
        "suggested_title": "How to monitor Reddit keyword mentions for free (Without buying expensive tracking software)",
        "ready_to_paste_content": "If you are bootstrapping a side project, you don't need to spend $99/mo on social monitoring tools. You can set up a high-quality alert pipeline for free in under 10 minutes.\n\nHere is the exact manual setup:\n\n1. Use F5Bot: Go to f5bot.com (it's completely free). Add your core product name and 2-3 competitor names. It checks Reddit and emails you when they are mentioned.\n2. Set up Google Alerts: Add site:reddit.com \"keyword\" to get indexed matches, though it can lag by 24-48 hours.\n3. Configure a custom multi-reddit: Group subreddits like r/SaaS, r/SideProject, and r/startups into one custom feed. Bookmark it and search for 'looking for alternative' or 'struggling with' once a day.\n\nThis covers 80% of what you need.\n\nIf you want to automate the tracking, filter matches semantically with AI, and draft responses in one place, I built RedLeads (redleads.app) as an alternative. But if you're just starting, the free stack above works perfectly.\n\nLet me know if you run into any issues setting up the filters!"
    },
    {
        "id": "day-7-dm",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 70,
        "title": "The DM Redirection Protocol",
        "description": "Convert public interest into private conversations where you can safely share product links.",
        "content": "# Master DM Redirection\n\nIf you want to keep your domain safe from Reddit's automated link filter, the best strategy is **DM Redirection**. This turns public comments into warm sales conversations.\n\n## The Redirection Flow\n1. Write a value-first response to an active question in the Command Center.\n2. At the end of the comment, say: *\"I wrote a short cheatsheet/built a tool that does this. Happy to DM it to anyone who needs it.\"*\n3. When users reply to your comment saying \"Send it to me please!\", send them a polite, friendly message containing your link.\n\nThis flow ensures that every link you send is *solicited*, meaning the user requested it. Reddit's spam filters rarely touch links sent to users who requested them first.",
        "action_link": null,
        "action_label": null,
        "day_number": 7,
        "estimated_minutes": 15,
        "warning_content": "NEVER cold DM users who have not explicitly replied to your comments or posts asking for a link. Sending unsolicited promotional links in DMs is an instant ToS violation and account suspension."
    },
    {
        "id": "day-8-pipeline",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 80,
        "title": "Lead Pipeline Management",
        "description": "Use bookmarks to track high-value threads and manage them like a CRM.",
        "content": "# Treat Reddit Like a CRM\n\nNot every matching thread is ready for an immediate pitch. Some threads are too fresh (you don't want to look desperate), and some need a few days to mature.\n\n## Using the Bookmark Tool\n1. When you see a thread where the poster is a perfect fit for your SaaS but you aren't ready to reply yet, click the **Bookmark icon** in the Command Center.\n2. This stores the post in your **Pipeline** tab.\n3. Every Friday, check your Pipeline. Look at the threads that have matured. Read what others have said, and jump in with a comprehensive, well-thought-out answer that stands out above the noise.",
        "action_link": "?tab=live",
        "action_label": "Open Pipeline",
        "day_number": 8,
        "estimated_minutes": 10,
        "warning_content": "Do not wait too long to respond. The sweet spot for comments is within 12-24 hours of posting. Anything older than 48 hours rarely gets read by anyone other than the original poster."
    },
    {
        "id": "day-9-power",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 90,
        "title": "Feed vs. Power Search",
        "description": "Utilize active historical search to find high-intent posts that keywords missed.",
        "content": "# Live Feed vs. Power Search\n\nRedLeads gives you two primary modes of operation. Knowing when to use each is crucial for scaling your leads:\n\n## The Live Feed (Passive)\n- Runs continuously in the background based on your keywords.\n- Use this for your 10-minute daily routine.\n\n## Power Search (Active)\n- Queries Reddit's historical index semantically across the last 30 days.\n- Use this during dedicated growth sprints.\n- **Example:** If you build a landing page builder, query: *\"anyone know how to set up custom domain on nextjs\"* or *\"why is my page loading slowly\"*. \n\nPower Search uncovers hidden threads where standard keyword alerts fail because the user used different phrasing.",
        "action_link": "?tab=live",
        "action_label": "Try Power Search",
        "day_number": 9,
        "estimated_minutes": 15,
        "warning_content": "Power Search queries match semantics, not just text. Keep your queries natural and question-oriented for the best matching results."
    },
    {
        "id": "day-10-niche",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 100,
        "title": "Niche Subreddit Discovery",
        "description": "Locate hyper-focused, low-competition subreddits where your buyers hang out.",
        "content": "# Avoid the Crowd: Niche Subreddits\n\nIf you build marketing software, trying to get traffic from r/marketing is incredibly hard. It is crowded, highly moderated, and full of other developers doing the exact same thing.\n\n## How to Find Niche Communities\n1. In your **Command Center**, review the subreddits where your best matching posts are coming from.\n2. Look for hyper-focused subreddits with 10k-50k members (e.g., r/CopywritingTips, r/EmailDeliverability, r/SEO_Advice).\n3. In these small communities, competition is low, moderators are more relaxed, and a single helpful answer can stay on the front page of the subreddit for days.",
        "action_link": "?tab=live",
        "action_label": "Review Lead Subreddits",
        "day_number": 10,
        "estimated_minutes": 15,
        "warning_content": "Small subreddits have tight-knit communities. If you join and immediately post your product, you will be flagged as an intruder. Always leave at least 3 high-value comments before sharing any links."
    },
    {
        "id": "day-11-prune",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 110,
        "title": "Data-Driven Keyword Pruning",
        "description": "Analyze your lead logs to refine keywords and remove noise.",
        "content": "# Clean Up Your Engine\n\nAfter 10 days of tracking, you will have accumulated high-match scores and irrelevant noise. It is time to prune your keyword engine.\n\n## The Pruning Framework\n1. Review your Bookmarks and past responses. Which keywords generated the best matches?\n2. Go to **Settings**.\n3. Delete keywords that brought in low-quality leads, spam, or irrelevant discussions.\n4. Refine broad phrases. If \"analytics\" is too broad, refine it to \"setting up event tracking\" or \"how to fix GA4\".\n\nKeeping your keywords highly specific keeps your 10-minute daily routine efficient and noise-free.",
        "action_link": "?tab=settings",
        "action_label": "Prune Keywords",
        "day_number": 11,
        "estimated_minutes": 15,
        "warning_content": "A high volume of leads is useless if they don't convert. Prioritize keyword quality and intent over the total number of matches in your feed."
    },
    {
        "id": "day-12-authority",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 120,
        "title": "Build Authority with Case Studies",
        "description": "Transition from comments to writing high-performing text posts that drive viral traffic.",
        "content": "# The Authority Post Playbook\n\nWhile comments build steady daily traffic, a single high-performing text post in a major subreddit can drive thousands of signups in a single weekend. Here is how to write one:\n\n## The \"Value-Bomb\" Post Formula\n- **The Hook:** A clear, metric-driven headline. \n  *Example: \"How I automated my client reporting to save 12 hours a week (With Python script)\"*\n- **The Story:** Describe the problem you faced, your failures, and the exact steps you took to build the solution.\n- **The Code/Data:** Share your data, metrics, or scripts directly in the post. Do not gate it behind a link.\n- **The Call to Action:** At the very end, add a soft mention: *\"I eventually packaged this script into a clean web app so my non-technical friends could use it. If anyone wants to try it, search for [Product] or drop me a DM.\"*\n\nThis format is highly shared, rarely deleted, and builds massive brand trust.",
        "action_link": null,
        "action_label": null,
        "day_number": 12,
        "estimated_minutes": 25,
        "warning_content": "Never post links to your site directly inside the main body of a text post in subreddits like r/startups or r/entrepreneur. If you do, automod will remove it instantly.",
        "target_subreddit": "r/startups",
        "suggested_title": "How we got our first 100 users with $0 ad spend using organic community replies",
        "ready_to_paste_content": "Hey everyone,\n\nJust hit a milestone of 100 registered users for our SaaS and wanted to share the exact acquisition funnel we used, because we did it with zero ad spend.\n\nHere is the raw breakdown of our traffic channels:\n- Organic Reddit Replies: 62%\n- Build in Public updates: 23%\n- Direct referrals: 15%\n\nWhat failed:\n- Cold Email: Sent 200 emails, got 4 replies, 0 conversions. It felt spammy and took too long to personalize.\n- Twitter/X: Unless you already have a big following, posting updates felt like screaming into an empty room.\n\nOur exact Reddit playbooks:\n1. The 10-Minute Daily Check: Every morning, we search for active threads where users are complaining about the specific problem we solve.\n2. Value-First comment anatomy: We write a detailed, 3-step manual solution. We never drop a link in the main reply. Instead, we write: 'I built a free tool to automate this. Let me know if you want the link and I'll send it over.'\n3. DM redirection: When they reply asking for it, we DM a friendly note. Our conversion rate from requested DMs to signups was 45%.\n\nIf you're building a B2B SaaS and struggling to find early users, try this manual workflow. Happy to answer any questions about our setup in the comments!"
    },
    {
        "id": "day-13-followup",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 130,
        "title": "Safe Thread Follow-Up",
        "description": "Learn the safe, non-spammy way to follow up on old threads publicly.",
        "content": "# The Public Follow-Up Protocol\n\nMany founders make the mistake of DMing users weeks after they post. This looks invasive and spammy. The correct, safe way to follow up is **publicly in the original thread**.\n\n## How to Follow Up Safely\n1. Open your Pipeline and find a thread that is 1-2 weeks old where you previously gave advice.\n2. Reply to your own original comment or the OP's comment with a public update.\n   *Example: \"Hey OP! Just checking in to see if you ended up resolving this event tracking issue? If you ended up going with X, how did it work out?\"*\n\nThis shows everyone reading the thread (including future search engine visitors) that you are a genuine, helpful consultant, and prompts the OP to reply, bumping your comment back to their notification tray.",
        "action_link": "?tab=live",
        "action_label": "Check Pipeline",
        "day_number": 13,
        "estimated_minutes": 15,
        "warning_content": "Never send cold private messages saying 'Hey, did you buy my tool?' This violates Reddit's guidelines on direct marketing and leads to user blocks."
    },
    {
        "id": "day-14-scale",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 140,
        "title": "Transition to the Flywheel",
        "description": "Transition your 14-day sprint into a continuous, evergreen acquisition channel.",
        "content": "# The Acquisition Flywheel\n\nCongratulations! You have completed the 14-day RedLeads OS sprint. You have moved from manual, risky Reddit spamming to managing a safe, high-intent lead intelligence pipeline.\n\n## Your Evergreen Routine\n1. **Daily (10 mins):** Scan the Command Center for Tier 1 matches. Respond with casual, value-first comments.\n2. **Weekly (30 mins):** Run a Power Search for specific queries to capture users researching alternatives. Check and reply to bookmarked leads in your Pipeline.\n3. **Monthly (1 hour):** Review conversions, prune underperforming keywords, and write a detailed case study or value-post to share in relevant subreddits.\n\nBy sticking to this loop, you turn Reddit into a predictable, free traffic source for your SaaS.",
        "action_link": "?tab=live",
        "action_label": "Open Command Center",
        "day_number": 14,
        "estimated_minutes": 10,
        "warning_content": "Reddit is a long-term play. Traffic from search engine indexed Reddit posts can continue to drive users to your SaaS months after you write the comment. Keep it clean and high-value.",
        "target_subreddit": "r/Entrepreneur",
        "suggested_title": "We launched on Product Hunt, finished as the #4 Product of the Day, and got 0 signups. Here is our post-mortem.",
        "ready_to_paste_content": "Last Tuesday was supposed to be our big launch day. We had spent 3 months preparing, got a top hunter, and finished as the #4 Product of the Day.\n\nTotal visitors: 1,200.\nTotal conversions: 0.\n\nIt was a gut punch. Here is the honest post-mortem of why our launch failed, so you don't make the same mistakes:\n\n1. The Value Prop was confusing: We thought our headline 'The ultimate community optimization intelligence engine' sounded professional. In reality, visitors had no idea what we actually did. When we ran user tests later, people said: 'I don't know what this does.'\n2. Friction in Onboarding: We required a Google OAuth login + workspace setup before showing the dashboard. 80% of visitors dropped off at the login screen.\n3. Lack of Social Proof: Our landing page had no testimonials, no video demo, and no screenshots of the dashboard. We asked visitors to buy on blind trust.\n\nHow we are fixing it:\n- Rewriting our headline to be direct: 'Get alerted when someone mentions your brand on Reddit.'\n- Adding a 30-second video demo at the top of the fold.\n- Letting users try the dashboard layout with dummy data before signing up.\n\nHas anyone else experienced a high-traffic, zero-conversion launch? How did you pivot your landing page copy?"
    }
];
