import { GuideNode } from '@/types/guide';

export const Guide_NODES: GuideNode[] = [
    {
        "id": "day-1-setup",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 10,
        "title": "Calibrating The Engine",
        "description": "Stop searching manually. Configure the AI to hunt for exact problems you solve.",
        "content": "# The AI Calibration\n\nYour success on Reddit depends entirely on the keywords you tell RedLeads to track. Give the AI the right targets, and it will do the heavy lifting.\n\n## 1. The Strategy\n- **Go to Settings:** Add 3-5 high-intent keywords.\n- **Focus on Pain:** Track phrases like \"tired of [competitor]\" or \"how do I [problem]\".\n- **Avoid Broad Terms:** A keyword like \"software\" will flood your feed with noise.\n\n## 2. Action Step\nClick **Setup Keywords** below and input your specific targets. RedLeads will immediately begin scanning Reddit for these exact phrases.",
        "action_link": "?tab=settings",
        "action_label": "Setup Keywords",
        "day_number": 1,
        "estimated_minutes": 10
    },
    {
        "id": "day-2-karma",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 20,
        "title": "The Karma Shield",
        "description": "Gain the trust of the Reddit algorithms without getting banned.",
        "content": "# Account Safety 101\n\nIf you drop links on day 1 with a fresh account, you *will* get banned. You need a Karma Shield.\n\n## The Strategy\n1. Go to Reddit (outside the app) and find subreddits related to your industry.\n2. **DO NOT** mention your product.\n3. Find 5 questions where you have genuine expertise.\n4. Write detailed, highly-valuable answers.\n\nThis builds your account's authority and prevents the automod from flagging you when you use the RedLeads AI Drafter later.",
        "action_link": "?tab=settings",
        "action_label": "Review Tracking",
        "day_number": 2,
        "estimated_minutes": 20
    },
    {
        "id": "day-3-competitor",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 30,
        "title": "The Competitor Ambush",
        "description": "Set up trackers to intercept unhappy competitor customers.",
        "content": "# Steal Their Leads\n\nThe easiest way to get users is to find people complaining about your competitors.\n\n## The Tactic\n1. Go back to your **Keyword Settings**.\n2. Add keywords like: \"hate [Competitor]\", \"tired of [Competitor]\", \"[Competitor] alternative\".\n3. Wait 24 hours. RedLeads will begin pulling angry competitor customers into your Command Center.\n\nOnce they appear, use the AI Drafter to send a highly empathetic reply introducing your platform as the better alternative.",
        "action_link": "?tab=settings",
        "action_label": "Add Competitors",
        "day_number": 3,
        "estimated_minutes": 5
    },
    {
        "id": "day-4-pitch",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 1,
        "order_index": 40,
        "title": "The Soft Pitch Masterclass",
        "description": "Tweak the AI Drafter's brain to improve conversions.",
        "content": "# Optimizing the AI Context\n\nThe AI Drafter relies entirely on your profile parameters.\n\n## Time to Iterate\nIf your AI replies feel too generic, update your context.\n1. Go to **Settings**.\n2. Rewrite your **Product Description**.\n3. **CRUCIAL:** Add a tone instruction to your description. *\"Speak casually, use lowercase, act like a solo-dev trying to be helpful.\"*\n\nThe smarter you make your RedLeads context, the less editing you have to do.",
        "action_link": "?tab=settings",
        "action_label": "Update Description",
        "day_number": 4,
        "estimated_minutes": 15
    },
    {
        "id": "day-5-routine",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 50,
        "title": "The 10-Minute Engine",
        "description": "Build an automated, hyper-efficient acquisition routine.",
        "content": "# The Passive Pipeline\n\nYou no longer need to spend hours a day on Reddit. Execute this strict routine every morning.\n\n## The Workflow\n1. Open the **Command Center**.\n2. Look at the top 3 high-scoring posts captured by the AI.\n3. Click **Draft Intelligence** to generate a perfectly tailored, non-spammy reply.\n4. Copy the reply, click the link to go to Reddit, and post it. Close the app.\n\nYou've just guaranteed 3 high-quality touchpoints with potential customers in under 10 minutes.",
        "action_link": "?tab=live",
        "action_label": "Go To Command Center",
        "day_number": 5,
        "estimated_minutes": 10
    },
    {
        "id": "day-6-value",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 60,
        "title": "Value-First Engagement",
        "description": "Master the art of the helpful reply using the Drafter.",
        "content": "# Give Before You Take\n\nReddit hates marketers. If your first sentence is \"Try my app!\", you fail.\n\n## The Strategy\nWhen using the AI Drafter in the **Command Center**:\n1. Ensure the generated reply answers the user's question *completely* without them needing to click your link.\n2. The link to your product should only exist as an \"Oh, by the way, I built a tool that automates step 3.\"\n\nIf the AI is too aggressive, hit regenerate before posting.",
        "action_link": "?tab=live",
        "action_label": "Practice Value-First",
        "day_number": 6,
        "estimated_minutes": 15
    },
    {
        "id": "day-7-bookmark",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 70,
        "title": "The CRM Pipeline",
        "description": "Treat the Command Center like your Reddit CRM.",
        "content": "# Don't Lose Them\n\nNot every lead is ready to buy today, and sometimes a thread is too new to reply to without looking desperate.\n\n## Task\n1. In the **Command Center**, click the **Bookmark icon** on posts that look like huge opportunities.\n2. This adds them to your saved Pipeline.\n3. Check your Pipeline every Friday to follow up on aging threads where the OP is still looking for a solution.",
        "action_link": "?tab=live",
        "action_label": "Bookmark a Lead",
        "day_number": 7,
        "estimated_minutes": 10
    },
    {
        "id": "day-8-search",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 80,
        "title": "Feed vs. Power Search",
        "description": "Know when to use passive scanning vs active hunting.",
        "content": "# The Two Modes\n\nRedLeads gives you two weapons: The Live Feed and Power Search.\n\n## The Live Feed (Command Center)\n- Use this daily for your 10-minute routine.\n- It brings the leads to you passively based on your keywords.\n\n## Power Search (Active)\n- Use this when you need a surge of users *today*.\n- Type in highly specific, semantic questions (e.g. \"how to migrate from X to Y\") to force the AI to hunt deep into Reddit archives across the last 30 days.\n- Great for weekend growth sprints.",
        "action_link": "?tab=live",
        "action_label": "Try Power Search",
        "day_number": 8,
        "estimated_minutes": 15
    },
    {
        "id": "day-9-discovery",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 90,
        "title": "Deep Power Search",
        "description": "Run advanced queries to find hidden buyers.",
        "content": "# Beyond the Obvious\n\nIf you sell marketing software, posting in r/marketing is a trap. It's crowded.\n\n## The Tactic\nUse **Power Search** to look for hyper-niche problems. When the results load, look at the subreddits the posts are coming from.\n\nYou might discover that your best leads aren't in r/SaaS, but hidden in r/EmailDeliverability or r/CopywritingTips. Focus your efforts where the competition is low.",
        "action_link": "?tab=live",
        "action_label": "Run a Deep Search",
        "day_number": 9,
        "estimated_minutes": 20
    },
    {
        "id": "day-10-consistency",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 2,
        "order_index": 100,
        "title": "The Consistency Check",
        "description": "Are you sticking to the 10-minute routine?",
        "content": "# The Flywheel is Turning\n\nBy day 10, your Command Center should be filled with high-quality AI matches. \n\n## The Goal\nYour only goal today is to log into the Command Center, find 3 great posts, generate Draft Intelligence replies, and post them. Do not spend more than 10 minutes. Consistency beats marathon sessions on Reddit.",
        "action_link": "?tab=live",
        "action_label": "Do the 10-Min Routine",
        "day_number": 10,
        "estimated_minutes": 10
    },
    {
        "id": "day-11-prune",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 110,
        "title": "Data-Driven Pruning",
        "description": "Review what keywords are bringing the best quality leads.",
        "content": "# The Data-Driven Marketer\n\nYou've been using RedLeads for a while. What's working?\n\n## The Tactic\nLook at your saved leads and successful conversions in the Command Center. Which keyword captured them?\nIf \"competitor alternative\" is bringing in 80% of your traffic, double down. Delete the broader keywords that just bring noise.\n\nLet the data dictate your tracking strategy.",
        "action_link": "?tab=settings",
        "action_label": "Prune Keywords",
        "day_number": 11,
        "estimated_minutes": 15
    },
    {
        "id": "day-12-domination",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 120,
        "title": "Subreddit Domination",
        "description": "Focus entirely on the subreddits that consistently yield high-score matches.",
        "content": "# Identifying the Goldmine\n\nBy now, your **Command Center** should show a pattern. Is there one subreddit popping up more often than the others with high AI match scores?\n\n## Action\nFocus 80% of your automated drafting time specifically on posts from this subreddit. Become a recognized, helpful authority in that specific community. Users will start recognizing your username.",
        "action_link": "?tab=live",
        "action_label": "Review Top Subreddits",
        "day_number": 12,
        "estimated_minutes": 10
    },
    {
        "id": "day-13-crm",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 130,
        "title": "The Follow-Up",
        "description": "Re-engage with your aging pipeline.",
        "content": "# The Fortune is in the Follow-Up\n\nOpen your **Pipeline** (bookmarks) in the Command Center.\n\nLook for users you drafted a reply to weeks ago. Are they still complaining? Did they find a solution?\n\nUse the AI Drafter to write a soft, non-pushy follow-up. \n*\"Hey! Saw your original post a while back. Did you end up finding a solution? If not, my tool does exactly this now.\"*",
        "action_link": "?tab=live",
        "action_label": "Check Pipeline",
        "day_number": 13,
        "estimated_minutes": 15
    },
    {
        "id": "day-14-scale",
        "created_at": "2026-02-07T17:24:08.346384+00:00",
        "phase": 3,
        "order_index": 140,
        "title": "Scale and Automate",
        "description": "You have fully automated your acquisition pipeline.",
        "content": "# The Flywheel\n\nYou've done it. You have transitioned from manually begging for users on Reddit to managing an automated intelligence pipeline.\n\n## The Final Setup\n1. Stick to your 10-minute routine, checking the Command Center daily.\n2. Run a Power Search every Friday for deep hunting.\n3. Keep adjusting your keywords in Settings as your product evolves.\n\nRedLeads is now your primary growth engine. You are ready to scale.",
        "action_link": "?tab=live",
        "action_label": "Scale the Routine",
        "day_number": 14,
        "estimated_minutes": 5
    }
];
